import { Product } from "./type";

export const products: Product[] = [
  // tops
  {
    id: 1,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/F19.webp"),
    // image:[require("../../../public/F19.webp")],
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 2,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/f21.webp"),
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 3,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/f22.webp"),
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 4,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/f23.webp"),
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 5,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/f24.jpeg"),
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 6,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    // image: ["/F4.avif", "/F9.avif"],
    image: require("../../../public/f25.jpeg"),
    slug: "brown-check-shirt",
    price: 300,
    discount: 0,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },

  // Pants
  {
    id: 7,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/J1.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 8,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/j2.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 9,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/j3.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 10,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/J4.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 11,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/j5.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 12,
    title: "Denim Classic Jeans for Effortless Style",
    // image: ["/m10.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    image: require("../../../public/j6.jpeg"),
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  //accesories
  {
    id: 13,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/ac1.avif"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 14,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/ac2.avif"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 15,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/ac3.webp"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 16,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/ac4.webp"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 17,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/avif5.avif"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 18,
    title: "Elegant Essentials: Accessorize Your Style",
    // image: ["/ac1.avif", "/ac2.avif", "ac4.avif", "ac4.avif"],
    image: require("../../../public/accesories2.avif"),
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  // shoes
  {
    id: 19,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes.avif"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 20,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes2.avif"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 21,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes3.avif"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 22,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes4.avif"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 23,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes5.avif"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 24,
    title: "Sleek Leather Oxford Shoes",
    // image: [
    //   "/shoes.avif",
    //   "/shoes2.avif",
    //   "shoes3.avif",
    //   "shoes4.avif",
    //   "shoes5.avif",
    // ],
    image: require("../../../public/shoes6.webp"),
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
];
