import { Product } from "./type";

export const products: Product[] = [
  // tops
  {
    id: 1,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F4.avif", "/F9.avif"],
    slug: "brown-check-shirts",
    price: 300,
    discount: 20,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#E26EE5", "#FFB534", "#495E57"],
    qty: 1,
  },
  {
    id: 2,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F9.avif", "/F4.avif"],
    slug: "brown-check-shirtx",
    price: 360,
    discount: 30,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#7E30E1"],
    qty: 1,
  },
  {
    id: 3,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F23.webp", "/F9.avif"],
    slug: "brown-check-shirtz",
    price: 380,
    discount: 40,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#ED7D31", "#F4CE14", "#D71313"],
    qty: 1,
  },
  {
    id: 4,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F19.webp", "/F21.webp"],
    slug: "brown-check-shirtss",
    price: 400, 
    discount: 20,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#E26EE5", "#FFB534", "#495E57"],
    qty: 1,
  },
  {
    id: 5,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/f22.webp", "/f21.webp"],
    slug: "brown-check-shirt--",
    price: 400,
    discount: 20,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 6,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F21.webp", "/F19.webp"],
    slug: "brown-check-shirt-",
    price: 400,
    discount: 20,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#E26EE5", "#FFB534", "#495E57"],
    qty: 1,
  },
  {
    id: 7,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/F21.webp", "/F19.webp"],
    slug: "brown-check-dress",
    price: 400,
    discount: 20,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#025464", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 8,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/p2.png", "/p1.png", "/p3.png"],
    slug: "shirt-dress1",
    price: 700,
    discount: 35,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#F86F03", "#994D1C"],
    qty: 1,
  },
  {
    id: 9,
    title: "Earthy Elegance: Classic Brown Plaid Shirt & Tops",
    image: ["/p1.png", "/p2.png", "/p3.png"],
    slug: "shirt-dress2",
    price: 650,
    discount: 38,
    category: "tops",
    description:
      "featuring intersecting lines in warm tones, offers a versatile and stylish wardrobe staple. Suitable for various occasions, it combines classic design with a contemporary touch.",
    size: ["S", "M", "L", "XL"],
    color: ["#F1C376", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  // Pants
  {
    id: 10,
    title: "Denim Classic Jeans for Effortless Style",
    image: ["/m10.avif", "/m11.avif", "/M2.avif"],
    slug: "denim-classic-jeans-for-effortless-style",
    price: 450,
    discount: 20,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#025464", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 11,
    title: "Denim Classic Jeans for EffortlessStyle",
    image: ["/M2.avif", "/m11.avif"],
    slug: "denim-classic-jeans-for-style",
    price: 470,
    discount: 30,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#482121", "#994D1C"],
    qty: 1,
  },
  {
    id: 12,
    title: "Denim Classic Jeans for Effortless Style",
    image: ["/m11.avif", "/m10.avif"],
    slug: "denim-classic-jeans-for-effortless-style1",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#47A992"],
    qty: 1,
  },
  {
    id: 13,
    title: "Denim Classic Jeans for Effortless Style",
    image: ["/M6.avif", "/M5.avif", "/M6.avif"],
    slug: "denim-classic-jeans-for-effortless-style2",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#C69774", "#994D1C"],
    qty: 1,
  },
  {
    id: 14,
    title: "Denim Classic Jeans for Effortless Style",
    image: ["/M7.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    slug: "denim-classic-jeans-for-effortless-style3",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#B80000", "#9BB8CD", "#994D1C"], 
    qty: 1,
  },
  {
    id: 15,
    title: "Denim Classic Jeans for Effortless Style",
    image: ["/M9.avif", "/m11.avif", "/M2.avif", "/M6.avif", "/M7.avif"],
    slug: "denim-classic-jeans-for-effortless-style5",
    price: 450,
    discount: 0,
    category: "pants",
    description:
      "Embrace timeless style with these classic blue jeans. The perfect blend of comfort and fashion, these denim essentials effortlessly take you from casual Fridays to weekend adventures.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#B80000", "#994D1C"],
    qty: 1,
  },
  //accesories
  {
    id: 16,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/ac1.avif", "/ac2.avif", "/ac4.webp", "/ac3.webp"],
    slug: "elegant-essentials-accessorize-your-style",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#B2A59B", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 17,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/ac2.avif", "/ac4.webp", "/ac3.webp"],
    slug: "elegant-essentials-accessorize-your-styles",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#F7B787"],
    qty: 1,
  },
  {
    id: 18,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/ac4.webp", "/ac1.avif", "/ac2.avif", "/ac3.webp"],
    slug: "elegant-essentials-accessorize-your-styless",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#607274"],
    qty: 1,
  },
  {
    id: 19,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/ac3.webp", "/ac2.avif", "/ac4.webp", "/ac1.avif"],
    slug: "elegant-essentials-accessorize-your-style-",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 20,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/accesories2.avif", "/ac2.avif", "/ac4.webp", "/ac3.webp"],
    slug: "elegant-essentials-accessorize-your-style1",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#47A992", "#F86F03", "#994D1C"],
    qty: 1,
  },
  {
    id: 21,
    title: "Elegant Essentials: Accessorize Your Style",
    image: ["/avif5.avif", "/ac2.avif", "/ac4.webp", "/ac3.webp"],
    slug: "elegant-essentials-accessorize-your-stylez",
    price: 500,
    discount: 0,
    category: "accessories",
    description:
      "Elevate your look with our collection of elegant accessories. From statement watches to classic belts, discover the perfect accents to express your unique style and sophistication.",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#C69774", "#994D1C"],
    qty: 1,
  },
  // shoes
  {
    id: 22,
    title: "Sleek Leather Oxford Shoes",
    image: [
      "/shoes.avif",
      "/shoes2.avif",
      "/shoes3.avif",
      "/shoes4.avif",
      "/shoes5.avif",
      "/shoes6.webp",
    ],
    slug: "sleek-leather-oxford-shoes",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#B80000", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 23,
    title: "Sleek Leather Oxford Shoes",
    image: [
      "/shoes2.avif",
      "/shoes.avif",
      "/shoes3.avif",
      "/shoes4.avif",
      "/shoes5.avif",
      "/shoes6.webp",
    ],
    slug: "sleek-leather-oxford-shoes-",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#9BB8CD", "#C69774", "#994D1C"],
    qty: 1,
  },
  {
    id: 24,
    title: "Sleek Leather Oxford Shoes",
    image: [
      "/shoes3.avif",
      "/shoes.avif",
      "/shoes2.avif",
      "/shoes4.avif",
      "/shoes5.avif",
      "/shoes6.webp",
    ],
    slug: "sleek-leather-oxford-shoe",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#C69774", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 25,
    title: "Sleek Leather Oxford Shoes",
    image: [
      "/shoes4.avif",
      "/shoes.avif",
      "/shoes2.avif",
      "/shoes3.avif",
      "/shoes5.avif",
      "/shoes6.webp",
    ],
    slug: "sleek-leather-oxford-shoesss",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#9BB8CD", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 26,
    title: "Sleek Leather Oxford Shoes3",
    image: [
      "/shoes5.avif",
      "/shoes.avif",
      "/shoes2.avif",
      "/shoes3.avif",
      "/shoes4.avif",
      "/shoes6.webp",
    ],
    slug: "sleek-leather-oxford-shoes!",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#C69774", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
  {
    id: 27,
    title: "Sleek Leather Oxford Shoes",
    image: [
      "/shoes6.webp",
      "/shoes.avif",
      "/shoes2.avif",
      "/shoes3.avif",
      "/shoes4.avif",
      "/shoes5.avif",
    ],
    slug: "sleek-leather-oxford-shoes5",
    price: 350,
    discount: 10,
    category: "shoes",
    description:
      "Elevate your style with these sleek leather Oxford shoes. Crafted for both sophistication and comfort, they effortlessly complement formal and casual attire for a timeless, polished look.",
    size: ["S", "M", "L", "XL"],
    color: ["#E26EE5", "#9BB8CD", "#994D1C"],
    qty: 1,
  },
];
